--- This is used for local testing
--- libvirt is preferred; vagrant's default is virtualbox, which is slow
--- libvirt is 3-10x faster for testing
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: "14.12.9"
  install_strategy: once
  always_update_cookbooks: true
  environments_path: test/environments
  data_bags_path: test/data_bags
  environment: kitchen
  driver_config:
    provider: libvirt

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      box: 'centos/7'
      customize:
        memory: 2048
  - name: debian-stretch
    driver:
      box: 'debian/stretch64'
      customize:
        memory: 2048
  - name: ubuntu-1604
    driver:
      box: 'generic/ubuntu1604'
      customize:
        memory: 2048

suites:
  - name: solr-lts-default
    run_list:
      - recipe[solr-lts::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
