AllCops:
  Exclude:
    - vendor/**/*
    - bin/*
    - spec/
    - metadata.rb
    - Berksfile
    - Rakefile
    - Gemfile

Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
